from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from chatenv import BaseEnvConfig, EnvField, EnvStore, get_paths

DEFAULT_BASE_URL = "http://127.0.0.1:3000"
DEFAULT_LISTEN_ADDR = "127.0.0.1"
DEFAULT_HTTP_PORT = 3000
DEFAULT_SERVICE_NAME = "chattea-gitea.service"


# Backwards-compatible alias for older callers that imported DEFAULT_URL.
DEFAULT_URL = DEFAULT_BASE_URL


def default_chattea_home() -> Path:
    return get_paths().home_dir / "chattea"


def default_gitea_binary(home: Path | None = None) -> Path:
    root = home or default_chattea_home()
    return root / "bin" / "gitea"


def default_gitea_work_path(home: Path | None = None) -> Path:
    root = home or default_chattea_home()
    return root / "gitea"


def default_gitea_config(work_path: Path | None = None, home: Path | None = None) -> Path:
    work = work_path or default_gitea_work_path(home)
    return work / "custom" / "conf" / "app.ini"


def normalize_base_url(value: str | None) -> str:
    url = str(value or DEFAULT_BASE_URL).strip().rstrip("/")
    parsed = urlparse(url)
    if parsed.scheme not in {"http", "https"} or not parsed.hostname:
        raise ValueError("Gitea base URL must be an http(s) URL, for example http://127.0.0.1:3000.")
    return url


def base_url_host(value: str) -> str:
    parsed = urlparse(normalize_base_url(value))
    return parsed.hostname or DEFAULT_LISTEN_ADDR


def validate_listen_addr(value: str | None) -> str:
    listen_addr = str(value or DEFAULT_LISTEN_ADDR).strip()
    if not listen_addr or "://" in listen_addr:
        raise ValueError("Gitea listen address must be an IP/host only, for example 127.0.0.1 or 0.0.0.0.")
    return listen_addr


def validate_http_port(value: Any, default: int = DEFAULT_HTTP_PORT) -> int:
    try:
        port = int(value if value not in (None, "") else default)
    except (TypeError, ValueError) as exc:
        raise ValueError("Gitea HTTP port must be an integer.") from exc
    if port < 1 or port > 65535:
        raise ValueError("Gitea HTTP port must be between 1 and 65535.")
    return port


class ChatTeaEnvConfig(BaseEnvConfig):
    """Typed ChatEnv configuration for ChatTea."""

    _title = "ChatTea Configuration"
    _aliases = ["chattea", "gitea", "tea"]
    _storage_dir = "ChatTea"

    CHATTEA_BASE_URL = EnvField(
        "CHATTEA_BASE_URL",
        default=DEFAULT_BASE_URL,
        desc="Gitea website/API base URL used by ChatTea and Gitea ROOT_URL.",
    )
    CHATTEA_TOKEN = EnvField(
        "CHATTEA_TOKEN",
        desc="Gitea API token used by ChatTea API commands.",
        is_sensitive=True,
    )
    CHATTEA_HOME = EnvField(
        "CHATTEA_HOME",
        default=str(default_chattea_home()),
        desc="ChatTea data root. Defaults to CHATARCH_HOME/chattea.",
    )
    CHATTEA_BINARY = EnvField(
        "CHATTEA_BINARY",
        default=str(default_gitea_binary()),
        desc="Gitea binary path. Defaults to CHATTEA_HOME/bin/gitea.",
    )
    CHATTEA_WORK_PATH = EnvField(
        "CHATTEA_WORK_PATH",
        default=str(default_gitea_work_path()),
        desc="Gitea work path. Defaults to CHATTEA_HOME/gitea.",
    )
    CHATTEA_CONFIG = EnvField(
        "CHATTEA_CONFIG",
        default=str(default_gitea_config()),
        desc="Gitea app.ini path. Defaults to CHATTEA_WORK_PATH/custom/conf/app.ini.",
    )
    CHATTEA_BOOTSTRAP_ADMIN_USER = EnvField(
        "CHATTEA_BOOTSTRAP_ADMIN_USER",
        default="gitea_admin",
        desc="Initial Gitea admin username used by server bootstrap.",
    )
    CHATTEA_BOOTSTRAP_ADMIN_EMAIL = EnvField(
        "CHATTEA_BOOTSTRAP_ADMIN_EMAIL",
        default="gitea_admin@example.invalid",
        desc="Initial Gitea admin email used by server bootstrap.",
    )
    CHATTEA_BOOTSTRAP_ADMIN_PASSWORD = EnvField(
        "CHATTEA_BOOTSTRAP_ADMIN_PASSWORD",
        desc="Initial Gitea admin password used only by server bootstrap.",
        is_sensitive=True,
    )
    CHATTEA_BOOTSTRAP_TOKEN_NAME = EnvField(
        "CHATTEA_BOOTSTRAP_TOKEN_NAME",
        default="default",
        desc="Initial Gitea access token name generated by server bootstrap.",
    )
    CHATTEA_BOOTSTRAP_TOKEN_SCOPES = EnvField(
        "CHATTEA_BOOTSTRAP_TOKEN_SCOPES",
        default="all",
        desc="Comma-separated initial Gitea access token scopes generated by server bootstrap.",
    )

    @classmethod
    def _refresh_dynamic_defaults(cls) -> None:
        updates = {
            "CHATTEA_HOME": str(default_chattea_home()),
            "CHATTEA_BINARY": str(default_gitea_binary()),
            "CHATTEA_WORK_PATH": str(default_gitea_work_path()),
            "CHATTEA_CONFIG": str(default_gitea_config()),
        }
        for attr, new_default in updates.items():
            field = getattr(cls, attr)
            old_default = field.default
            field.default = new_default
            if field.value in (None, old_default):
                field.value = new_default

    @classmethod
    def get_fields(cls) -> dict[str, EnvField]:
        cls._refresh_dynamic_defaults()
        return super().get_fields()

    @classmethod
    def test(cls) -> None:
        """Validate local ChatEnv values without touching the Gitea network endpoint."""
        config = load_config()
        normalize_base_url(config.url)
        for name, path in {
            "CHATTEA_HOME": config.home,
            "CHATTEA_BINARY": config.gitea_binary,
            "CHATTEA_WORK_PATH": config.gitea_work_path,
            "CHATTEA_CONFIG": config.gitea_config,
        }.items():
            if path is None:
                raise ValueError(f"{name} did not resolve to a path.")
        print("ChatTea configuration looks valid.")


@dataclass
class ChatTeaConfig:
    url: str = DEFAULT_BASE_URL
    token: str | None = None
    home: Path | None = None
    gitea_binary: Path | None = None
    gitea_work_path: Path | None = None
    gitea_config: Path | None = None
    bootstrap_admin_user: str = "gitea_admin"
    bootstrap_admin_email: str = "gitea_admin@example.invalid"
    bootstrap_admin_password: str | None = None
    bootstrap_token_name: str = "default"
    bootstrap_token_scopes: str = "all"

    @property
    def base_url(self) -> str:
        return self.url

    @classmethod
    def from_mapping(cls, data: dict[str, Any]) -> "ChatTeaConfig":
        url = data.get("base_url") or data.get("url") or DEFAULT_BASE_URL
        return cls(url=normalize_base_url(str(url)), token=data.get("token") or None)

    def to_mapping(self) -> dict[str, Any]:
        data: dict[str, Any] = {"base_url": normalize_base_url(self.url)}
        if self.token:
            data["token"] = self.token
        return data


def get_config_path() -> Path:
    """Return the legacy JSON config path kept for read-only compatibility."""
    override = os.environ.get("CHATTEA_LEGACY_CONFIG")
    if override:
        return Path(override).expanduser()
    config_home = Path(os.environ.get("XDG_CONFIG_HOME", "~/.config")).expanduser()
    return config_home / "chattea" / "config.json"


def _load_legacy_config(path: Path | None = None) -> ChatTeaConfig:
    config_path = path or get_config_path()
    if not config_path.exists():
        return ChatTeaConfig()
    try:
        return ChatTeaConfig.from_mapping(json.loads(config_path.read_text(encoding="utf-8")))
    except (OSError, json.JSONDecodeError, ValueError):
        return ChatTeaConfig()


def _active_env_values() -> dict[str, str]:
    return EnvStore(get_paths().envs_dir).load_active(ChatTeaEnvConfig)


def _optional_path(value: Any) -> Path | None:
    if value in (None, ""):
        return None
    return Path(str(value)).expanduser()


def _explicit_value(key: str, active_values: dict[str, str]) -> str | None:
    value = os.getenv(key)
    if value not in (None, ""):
        return value
    value = active_values.get(key)
    if value not in (None, ""):
        return value
    return None


def _first_explicit(active_values: dict[str, str], *keys: str) -> str | None:
    for key in keys:
        value = _explicit_value(key, active_values)
        if value not in (None, ""):
            return value
    return None


def _safe_base_url(value: str | None) -> str:
    try:
        return normalize_base_url(value)
    except ValueError:
        return DEFAULT_BASE_URL


def load_config(path: Path | None = None) -> ChatTeaConfig:
    """Load ChatTea config from ChatEnv, with legacy JSON read fallback."""
    active_values = _active_env_values()
    BaseEnvConfig.load_all(get_paths().envs_dir)
    legacy = _load_legacy_config(path)

    explicit_url = _first_explicit(active_values, "CHATTEA_BASE_URL", "CHATTEA_GITEA_BASE_URL", "CHATTEA_URL")
    explicit_token = _explicit_value("CHATTEA_TOKEN", active_values)

    home = _optional_path(_explicit_value("CHATTEA_HOME", active_values)) or default_chattea_home()
    binary = _optional_path(_first_explicit(active_values, "CHATTEA_BINARY", "CHATTEA_GITEA_BINARY")) or default_gitea_binary(home)
    work_path = _optional_path(_first_explicit(active_values, "CHATTEA_WORK_PATH", "CHATTEA_GITEA_WORK_PATH")) or default_gitea_work_path(home)
    config_path = _optional_path(_first_explicit(active_values, "CHATTEA_CONFIG", "CHATTEA_GITEA_CONFIG")) or default_gitea_config(work_path)

    return ChatTeaConfig(
        url=_safe_base_url(explicit_url or legacy.url or DEFAULT_BASE_URL),
        token=explicit_token if explicit_token is not None else legacy.token,
        home=home,
        gitea_binary=binary,
        gitea_work_path=work_path,
        gitea_config=config_path,
        bootstrap_admin_user=_explicit_value("CHATTEA_BOOTSTRAP_ADMIN_USER", active_values) or "gitea_admin",
        bootstrap_admin_email=_explicit_value("CHATTEA_BOOTSTRAP_ADMIN_EMAIL", active_values) or "gitea_admin@example.invalid",
        bootstrap_admin_password=_explicit_value("CHATTEA_BOOTSTRAP_ADMIN_PASSWORD", active_values),
        bootstrap_token_name=_explicit_value("CHATTEA_BOOTSTRAP_TOKEN_NAME", active_values) or "default",
        bootstrap_token_scopes=_explicit_value("CHATTEA_BOOTSTRAP_TOKEN_SCOPES", active_values) or "all",
    )


def save_config(config: ChatTeaConfig, path: Path | None = None) -> Path:
    """Save URL/token to the active ChatTea ChatEnv profile."""
    store = EnvStore(get_paths().envs_dir)
    values = store.load_active(ChatTeaEnvConfig)
    values["CHATTEA_BASE_URL"] = normalize_base_url(config.url)
    if config.token:
        values["CHATTEA_TOKEN"] = config.token
    return store.save_active(ChatTeaEnvConfig, values)


def set_token(url: str, token: str, path: Path | None = None) -> Path:
    config = load_config(path)
    config.url = normalize_base_url(url)
    config.token = token
    return save_config(config, path)


def mask_token(token: str | None) -> str:
    if not token:
        return "<none>"
    if len(token) <= 12:
        return token[:2] + "..." + token[-2:]
    return token[:7] + "..." + token[-5:]


__all__ = [
    "ChatTeaConfig",
    "ChatTeaEnvConfig",
    "DEFAULT_BASE_URL",
    "DEFAULT_HTTP_PORT",
    "DEFAULT_LISTEN_ADDR",
    "DEFAULT_SERVICE_NAME",
    "DEFAULT_URL",
    "base_url_host",
    "default_chattea_home",
    "default_gitea_binary",
    "default_gitea_config",
    "default_gitea_work_path",
    "get_config_path",
    "load_config",
    "mask_token",
    "normalize_base_url",
    "save_config",
    "set_token",
    "validate_http_port",
    "validate_listen_addr",
]
